juspay/superposition

- crates/experimentation_platform/src/db/models.rs
- crates/frontend/src/pages/Home/Home.rs
Resolve screen converts all the values of dimensions to lower case
Do not lowercase dimension inputs while resolving
> fix: Do not lowercase dimension inputs while resolving

- crates/context_aware_config/src/api/functions/handlers.rs
- crates/context_aware_config/src/validation_functions.rs
- crates/frontend/src/components/function_form/function_form.rs
- crates/frontend/src/pages/function/function_create.rs
fixed function template
fixed function template
N.A.
N.A.
N.A.
N.A.
N.A.
> fix: fixed function template

- .github/workflows/nix.yaml
- rust.nix
See https://github.com/juspay/superposition/pull/20#pullrequestreview-2037395407
> chore(ci): Build using Nix (Ubuntu & macOS)

- clients/js/package.json
- cog.toml
Changes in js or haskell client do not trigger release tag creation
Add release tag generation for js and haskell client
> feat: Add release tag generation for js and haskell client

- crates/superposition_types/src/lib.rs
- scripts/create-tenant.sh
Open source users may not want the juspay email address in all their testing data when auth is disabled
Change the default email address from superposition@juspay.in to user@superposition.io
> fix: remove juspay email address for anon user

- crates/context_aware_config/src/validation_functions.rs
- crates/superposition/src/main.rs
The first page the user to be redirected to the default config page.
The first page the user is redirected to the default config page.
> fix: for the first page redirect to default config page

- crates/context_aware_config/src/api/context/handlers.rs
- crates/context_aware_config/src/api/context/types.rs
- crates/context_aware_config/src/helpers.rs
- postman/cac.postman_collection.json
- postman/cac/Context/.meta.json
- postman/cac/Context/Recompute Priority Context/.event.meta.json
- postman/cac/Context/Recompute Priority Context/event.prerequest.js
- postman/cac/Context/Recompute Priority Context/event.test.js
- postman/cac/Context/Recompute Priority Context/request.json
After any dimension update, contexts priority needs to be updated
Implemented Api inside context handler
NA
NA
NA
| {host}/context/context/priority/recompute    | PUT | NA | { "message": "Contexts priority updated successfully"} |
NA
> recompute priority Api for context

- crates/context_aware_config/src/api/context/handlers.rs
- crates/frontend/src/api.rs
- crates/frontend/src/components/context_form/context_form.rs
- crates/frontend/src/components/context_form/utils.rs
- crates/frontend/src/components/default_config_form/default_config_form.rs
- crates/frontend/src/components/drawer/drawer.rs
- crates/frontend/src/components/override_form/override_form.rs
- crates/frontend/src/pages/ContextOverride/context_override.rs
- crates/frontend/src/types.rs
> feat: added support for update , create and clone of override

- crates/frontend/src/components/context_form/context_form.rs
- crates/frontend/src/pages/ContextOverride/context_override.rs
- crates/frontend/src/utils.rs
> fix: fixed override_flow

- .editorconfig
- .github/workflows/ci_merge_main.yaml
- .github/workflows/nix.yaml
Formatting and ECLINT issue for yaml files
Add separate rule for yaml files
> fix: Formatting and ECLINT issue

- Cargo.lock
- Cargo.toml
- crates/context_aware_config/src/api/config/handlers.rs
- crates/frontend/Cargo.toml
- crates/frontend/src/pages/ContextOverride/context_override.rs
- crates/frontend/src/pages/default_config/default_config.rs
- crates/frontend/src/utils.rs
Enable grouping toggle in default configs does not persist
Added local storage support and grouping toggle in default configs persists now
> feat: Add local storage support

- crates/frontend/src/utils.rs
All APIs from the front-end should be done to paths relative to the domain used to host the frontend application.  The API endpoints used by frontend - should not be hard-coded as the application can be hosted on any domain name.
Change log:
- fixed usage of __APP_ENV
- if the APP_ENV's host value is set as "" or "/", the paths for api calls are taken relative to frontend's host origin
> feat: Support relative path for frontend

- crates/frontend/src/components.rs
- crates/frontend/src/components/context_card.rs
- crates/frontend/src/components/context_form.rs
- crates/frontend/src/components/default_config_form.rs
- crates/frontend/src/components/dimension_form.rs
- crates/frontend/src/components/dropdown.rs
- crates/frontend/src/components/experiment_form.rs
- crates/frontend/src/components/experiment_form/types.rs
- crates/frontend/src/components/experiment_form/utils.rs
- crates/frontend/src/components/override_form.rs
- crates/frontend/src/components/variant_form.rs
- crates/frontend/src/pages/context_override.rs
- crates/frontend/src/pages/custom_types.rs
- crates/frontend/src/pages/default_config.rs
- crates/frontend/src/pages/experiment.rs
- crates/frontend/src/pages/function.rs
- crates/frontend/src/pages/function/function_create.rs
- crates/frontend/src/pages/function/function_list.rs
- crates/frontend/src/pages/home.rs
- crates/frontend/src/types.rs
- crates/frontend/src/utils.rs
Keys in override form were displayed in alphabetic order rather than in the order of addition
We use Map<String, Value> to store the keys value pair of override form which being a Binary tree has it stored in alphabetic order, change this to use a vec of tuples.
> fix: display order of override keys

- crates/frontend/src/utils.rs
Parsing failed for values when type mentioned in schema had multiple value such as `{ type: ["null", "string"] }`.
Try parsing for all possible types mentioned in the `type` property, return the parsed value for whichever type it succeeds
> fix: handled parsing for multiple possible types

- crates/context_aware_config/src/api/default_config/handlers.rs
> fix: default config regex validation

- docs/client-context-aware-configuration.md
- integrating nix client in haskel repo, but the doc shared contains older url from bitbucket
- updated nix package addition docs
- NA
- NA
- NA
- NA
> updated nix client package addition docs

- crates/frontend/src/utils.rs
For number in context, it would consider it as an integer as whole, even if it was an array
Fixed the parsing for number
> fix: Fix context parsing

- crates/frontend/src/components/default_config_form.rs
- crates/frontend/src/components/dimension_form.rs
> Fix type template dropdown and form issues

- cog.toml
> fix: add superposition_macros in cog.toml to upgrade versions

- package-lock.json
- package.json
Proxy not getting enabled while using axios
Upgrade axios version
> fix: update axios version for function

- crates/context_aware_config/package-lock.json
- crates/context_aware_config/package.json
- crates/context_aware_config/src/validation_functions.rs
Version upgrade for axios to support proxy
update axios version in cac crate
> fix: update axios version in cac crate

- crates/context_aware_config/src/api/config/handlers.rs
- crates/context_aware_config/src/api/config/helpers.rs
- crates/frontend/src/components/context_form.rs
- crates/frontend/src/components/dropdown.rs
- crates/frontend/src/components/input_components.rs
- crates/frontend/src/pages/home.rs
- Resolve API didn't work for boolean values because of parsing query params
- Resolve page enum and toggle didn't work
- Resolve page un-strike of the resolved config didn't work
Solved the above issues
https://github.com/user-attachments/assets/34a0f36c-3112-48d5-925c-f9fdfced28e3
> fix: resolve page issue

- crates/context_aware_config/migrations/2024-04-22-122806_config_verions/down.sql
- crates/context_aware_config/migrations/2024-05-06-133756_type_templates/down.sql
- crates/context_aware_config/migrations/2024-05-06-133756_type_templates/up.sql
- crates/context_aware_config/migrations/2024-07-31-065515_add_last_modified_by/down.sql
- crates/context_aware_config/migrations/2024-07-31-065515_add_last_modified_by/up.sql
- crates/context_aware_config/src/api/context/handlers.rs
- crates/context_aware_config/src/api/default_config/handlers.rs
- crates/context_aware_config/src/api/dimension/handlers.rs
- crates/context_aware_config/src/api/functions/handlers.rs
- crates/context_aware_config/src/api/type_templates/handlers.rs
- crates/context_aware_config/src/db/models.rs
- crates/context_aware_config/src/db/schema.rs
- postman/cac.postman_collection.json
- postman/cac/Context/Get Context/event.test.js
- postman/cac/custom types/Create Type/event.test.js
- postman/cac/custom types/Get Types/event.test.js
> Add last modified for audit log

- crates/frontend/src/components/dropdown.rs
https://github.com/user-attachments/assets/4d1d755c-3741-4a47-b434-d5f85a6376be
> fix: dropdown search

- .env.example
- crates/context_aware_config/src/api/config/handlers.rs
- crates/context_aware_config/src/api/context/handlers.rs
- crates/context_aware_config/src/api/context/helpers.rs
- crates/context_aware_config/src/api/dimension/handlers.rs
- crates/context_aware_config/src/api/dimension/types.rs
- crates/frontend/src/components/context_form.rs
- crates/frontend/src/components/default_config_form.rs
- crates/frontend/src/components/input_components.rs
- crates/frontend/src/components/override_form.rs
- crates/frontend/src/pages/context_override.rs
- crates/frontend/src/pages/dimensions.rs
- crates/frontend/src/types.rs
- crates/service_utils/src/service/types.rs
- crates/superposition/src/main.rs
Mandatory Dimensions Feature
`MANDATORY_DIMENSIONS="dev:clientId,fare;test:fare"`
https://github.com/user-attachments/assets/44cbe739-ebaa-466f-b6b4-e34a1b0805c2
> feat: Mandatory dimensions feature

- Cargo.lock
- crates/context_aware_config/src/api/default_config/handlers.rs
- crates/context_aware_config/src/api/default_config/types.rs
- crates/context_aware_config/src/api/dimension/handlers.rs
- crates/context_aware_config/src/api/dimension/types.rs
- crates/context_aware_config/src/api/functions/handlers.rs
- crates/context_aware_config/src/api/functions/types.rs
- crates/context_aware_config/src/api/type_templates/handlers.rs
- crates/context_aware_config/src/api/type_templates/types.rs
- crates/superposition/src/main.rs
- crates/superposition_types/Cargo.toml
- crates/superposition_types/src/lib.rs
We need strong type validation for reduce repetitive checks
Added newtypes and validation for name field of default_config, functions, type templates , dimension, also added priority type for dimension
for path type value , when validation fails it was giving 404 notfound error , that's why overriden pathconfig error in app_data
NA
NA
NA
NA
> fix: newtypes for entity fiels

- crates/context_aware_config/src/validation_functions.rs
The 2s time limit for functions is too small for URL validation
Increase the time limit to 10s
> fix: update function time from 2s to 10s for network requests

- clients/go/Readme.md
- clients/go/cacclient/main.go
- clients/go/expclient/main.go
- clients/go/go.mod
- clients/go/main.go
> feat: adding go cac and experimentation client wrapper

- clients/go/Readme.md
- clients/go/go.mod
- flake.nix
Wrong module path
Fix the path and update the docs
> Go cac client

- clients/python/cacclient/__init__.py
- clients/python/cacclient/client.py
- clients/python/expclient/client.py
- clients/python/main.py
- crates/cac_client/src/lib.rs
- crates/experimentation_client/src/interface.rs
> fix: python client

- example.Dockerfile
wrong web assets path
change it to the correct path
> fix: example dockerfile

- README.md
Update docs with correct social icons and include logo
Updated doc
NA
NA
NA
NA
> docs: update docs with correct icons and include logo

- crates/frontend/src/components/condition_pills.rs
- crates/frontend/src/components/condition_pills/types.rs
- crates/frontend/src/components/context_card.rs
- crates/frontend/src/components/context_form.rs
- crates/frontend/src/components/context_form/utils.rs
- crates/frontend/src/components/experiment.rs
- crates/frontend/src/components/experiment_form.rs
- crates/frontend/src/components/experiment_form/utils.rs
- crates/frontend/src/pages/context_override.rs
- crates/frontend/src/pages/experiment.rs
- crates/frontend/src/pages/experiment_list.rs
- crates/frontend/src/pages/experiment_list/utils.rs
- crates/frontend/src/pages/home.rs
- crates/frontend/src/types.rs
- crates/frontend/src/utils.rs
Enhance context form and display unsupported operators in override UI
> fix: Display unsupported operators in override UI and enhance Context Form

- crates/frontend/src/components/context_card.rs
- crates/frontend/src/components/input.rs
> fix: removed edit option for experiment conditions

- README.md
Discord link expired
Created permanent invite link and used it.
NA
NA
NA
NA
NA
> docs: use permanent discord invite link

- .github/workflows/docker_image_gen.yaml
- .github/workflows/example_docker_image_gen.yaml
Push docker images to github container registries
> chore: add github container registry as a target

- crates/frontend/src/components/side_nav.rs
Sidenav loading only after wasm file is fetched
set the initial values of the side nav list and avoid adding effects
> fix: SideNav initial hydration delay issue

- crates/context_aware_config/src/api/config/handlers.rs
- crates/context_aware_config/src/api/config/helpers.rs
add prefix filter in resolve endpoint
> fix: add prefix filter in resolve endpoint

- Cargo.lock
- Cargo.toml
- cog.toml
- crates/experimentation_platform/Cargo.toml
- crates/experimentation_platform/src/api/experiments/handlers.rs
- crates/experimentation_platform/src/api/experiments/helpers.rs
- crates/experimentation_platform/src/api/experiments/types.rs
- crates/experimentation_platform/src/db/models.rs
- crates/experimentation_platform/tests/experimentation_tests.rs
- crates/superposition_derives/Cargo.toml
- crates/superposition_derives/src/lib.rs
using Value type in model.rs for Variants
use proper type for Variants in models instead of serde_json::Value type
> feat: Use Variant type in model

- crates/frontend/src/components/side_nav.rs
- crates/frontend/src/pages/config_version_list.rs
> fix: added base for single config version page

- crates/frontend/src/components/context_form.rs
Data for in operator is getting stringified from frontend
Parse string data to determine if it is JSON literal or not
> fix: Override dimension input for in operator

- crates/context_aware_config/src/api/config/handlers.rs
- crates/context_aware_config/src/api/default_config/handlers.rs
- crates/context_aware_config/src/api/dimension/handlers.rs
- crates/context_aware_config/src/api/functions/handlers.rs
- crates/context_aware_config/src/api/type_templates/handlers.rs
- crates/context_aware_config/src/api/type_templates/types.rs
- crates/experimentation_platform/src/api/experiments/handlers.rs
- crates/experimentation_platform/src/api/experiments/types.rs
- crates/frontend/src/api.rs
- crates/frontend/src/components/default_config_form.rs
- crates/frontend/src/components/dimension_form.rs
- crates/frontend/src/pages/config_version_list.rs
- crates/frontend/src/pages/context_override.rs
- crates/frontend/src/pages/custom_types.rs
- crates/frontend/src/pages/default_config.rs
- crates/frontend/src/pages/dimensions.rs
- crates/frontend/src/pages/experiment.rs
- crates/frontend/src/pages/experiment_list.rs
- crates/frontend/src/pages/function/function_list.rs
- crates/frontend/src/pages/home.rs
- crates/frontend/src/types.rs
- crates/frontend/src/utils.rs
- crates/superposition_types/src/custom_query.rs
- postman/cac/custom types/Get Types/event.test.js
Add pagination to dimension and default_config list APIs
https://github.com/user-attachments/assets/3bb751c0-f6c8-4e2d-a760-b7c8d3692efa
> fix: Add pagination to list APIs

- crates/frontend/src/components/context_form/utils.rs
- crates/frontend/src/utils.rs
In cases where a user enters as input a string which is a number, our parsing fails
add support for it
> fix: properly parsing numbers that are strings

- crates/frontend/src/pages/context_override.rs
Create override was broken with mandatory dimension
https://github.com/user-attachments/assets/0ae57a6e-743d-4bc3-be90-6e77cf1eeca6
https://github.com/user-attachments/assets/3d83db45-cf8f-417b-be6b-6c7cdb53c043
https://github.com/user-attachments/assets/f8d0a5c6-1662-40b2-9f35-c16d671b0389
> fix: mandatory dimension UI

- .github/workflows/example_docker_image_gen.yaml
- Cargo.lock
- Cargo.toml
- crates/superposition/Cargo.toml
- crates/superposition/src/auth/mod.rs
- crates/superposition/src/auth/saml2.rs
- crates/superposition/src/main.rs
- example.Dockerfile
- flake.nix
- nix/rust.nix
- saml-idp-meta.xml
> [WIP] SAML2 Auth Integration

- crates/experimentation_platform/src/api/experiments/handlers.rs
filtering on from and to date even after passing `all` in query params for experiments list api
Removed date based filtering in case `all` is passed in query params
> fix: disregarding experiments last-modified filter in case of `all`

- crates/service_utils/src/helpers.rs
- crates/superposition_types/src/webhook.rs
Make custom_headers and service_headers optional
> fix: webhook optional field

- docker-compose/postgres/db_init.sql
> feat: position migration update for demo up

- crates/experimentation_platform/src/api/experiments/handlers.rs
> fix: webhook payload

- crates/context_aware_config/src/api/default_config/handlers.rs
- crates/context_aware_config/src/api/default_config/types.rs
- crates/frontend/src/components/default_config_form.rs
- crates/frontend/src/components/default_config_form/types.rs
- crates/frontend/src/components/default_config_form/utils.rs
- postman/cac/Default Config/Add default-config key/request.json
- postman/cac/Default Config/Default-Config Add Key Failure-Invalid-Regex/request.json
- postman/cac/Default Config/Default-Config Add Key Failure/request.json
- postman/cac/Default Config/Delete default-config key/event.prerequest.js
- postman/experimentation-platform/Create Experiment 2/event.prerequest.js
- postman/experimentation-platform/Create Experiment/event.prerequest.js
- postman/experimentation-platform/Update Override Keys/event.prerequest.js
> feat: added update api for default config

- crates/frontend/src/api.rs
- crates/frontend/src/app.rs
- crates/frontend/src/components.rs
- crates/frontend/src/components/workspace_form.rs
- crates/frontend/src/components/workspace_form/types.rs
- crates/frontend/src/components/workspace_form/utils.rs
- crates/frontend/src/pages.rs
- crates/frontend/src/pages/workspace.rs
- crates/superposition/src/workspace.rs
- crates/superposition/src/workspace/handlers.rs
- crates/superposition_types/src/database.rs
- crates/superposition_types/src/database/models.rs
- crates/superposition_types/src/database/schema.rs
> Workspace UI

- crates/experimentation_platform/src/api/experiments/handlers.rs
- crates/service_utils/src/helpers.rs
- crates/service_utils/src/service/types.rs
- crates/superposition/src/app_state.rs
kms decrypt auth key in webhook call.
Added kms client in Appstate.
> fix: webhook kms decrypt auth key

- crates/frontend/src/components/context_form.rs
- crates/frontend/src/components/input.rs
- crates/frontend/src/logic.rs
The width of the toggle component was not static and could change based on class
Force the size of the toggle component to be constant
> Fix context form for inputs

- clients/haskell/hs-cac-client/src/Client.hs
- clients/haskell/hs-exp-client/src/Client.hs
Emoji is not getting parsed correctly with haskell client
Changes `newCAString, peekCAString` to `newCString, peekCstring`
reason being former encodes and decodes based on locale configuration 
with the later we are fixing it to utf8 encoding , decoding
> fix: haskell client encode fix

- crates/context_aware_config/src/api/context/handlers.rs
- crates/context_aware_config/src/api/context/types.rs
- crates/frontend/src/hoc/layout.rs
- crates/superposition/src/organisation/handlers.rs
> fix: Resolving general pending issues

- .github/workflows/ci_check_pr.yaml
- docker-compose.yaml
- flake.nix
- makefile
- Removed nested/recursive make calls in targets.
- Made docker conditonal, w/ podman as an alternative.
- Fixed deprecation warning in compose.
> Refactored Makefile

- crates/context_aware_config/src/api/config/handlers.rs
- crates/context_aware_config/src/api/context/handlers.rs
- crates/context_aware_config/src/api/context/helpers.rs
- crates/context_aware_config/src/api/context/operations.rs
- crates/context_aware_config/src/api/dimension/handlers.rs
- crates/context_aware_config/src/helpers.rs
- crates/superposition_types/src/lib.rs
Mandatory dimensions broke due to deprecation of TenantConfig
Support mandatory dimensions through workspace table
> Fix mandatory dimensions

- crates/service_utils/src/service/types.rs
When prepared statement caching is enabled, queries from previous workspaces may be served to other workspaces in the system during to the cache not including the schema name
Turn off prepared statement caching for now
This change worsens performance, we need to find a permanent fix in our diesel fork
> fix: disable prepared statement cache

- crates/frontend/src/pages/default_config.rs
prefix grouping is not redirecting to the correct URL
Add org_id which was missed here
> fix: prefix grouping was not redirecting to the correct URL

- crates/frontend/src/pages/function.rs
Functions page is aligned wrong
Change from flex-row to flex-col. Earlier both were present and the wrong one was deleted
> fix: function page alignment

- Cargo.lock
- Dockerfile
- crates/frontend/Cargo.toml
- makefile
> fix: update rust-monaco version

- crates/context_aware_config/src/api/context/handlers.rs
- crates/context_aware_config/src/api/context/helpers.rs
- crates/context_aware_config/src/api/context/operations.rs
- crates/context_aware_config/src/api/context/types.rs
- crates/experimentation_platform/src/api/experiments/handlers.rs
- crates/experimentation_platform/src/api/experiments/types.rs
- crates/frontend/src/components/experiment_form.rs
- crates/frontend/src/components/experiment_form/types.rs
- crates/frontend/src/components/experiment_form/utils.rs
Fields not being passed while updating experiments
Updating contract in frontend (Not the best fix)
> fix: Update experiments page

- .github/workflows/ci_merge_main.yaml
> chore: Pin cargo-edit and cocogitto in github action

- crates/experimentation_platform/src/api/experiments/handlers.rs
1. In error case, we are simply ignoring it while creating and updating experiments
2. change_reason and description not being updated while updating experiments
> fix: Unsafe error handling in experimentation

- Cargo.lock
- crates/service_utils/src/middlewares/tenant.rs
- crates/service_utils/src/service/types.rs
- crates/superposition/Cargo.toml
- crates/superposition/Superposition.cac.toml
- crates/superposition/src/app_state.rs
- crates/superposition/src/main.rs
- crates/superposition_types/src/lib.rs
- crates/superposition_types/src/webhook.rs
> fix: tenant config

- crates/frontend/src/components/context_card.rs
- crates/frontend/src/components/experiment.rs
- crates/frontend/src/components/table.rs
- crates/frontend/src/components/table/types.rs
- crates/frontend/src/pages/config_version_list.rs
- crates/frontend/src/pages/custom_types.rs
- crates/frontend/src/pages/default_config.rs
- crates/frontend/src/pages/dimensions.rs
- crates/frontend/src/pages/experiment_list.rs
- crates/frontend/src/pages/experiment_list/utils.rs
- crates/frontend/src/pages/function/function_list.rs
- crates/frontend/src/pages/function/utils.rs
- crates/frontend/src/pages/organisations.rs
- crates/frontend/src/pages/workspace.rs
- crates/frontend/styles/tailwind.css
Needed to scroll horizontally for larger values.
Added a new component to expand and condense the text and fixed the first column.
https://github.com/user-attachments/assets/61f27df4-1ab2-4356-a1f7-3decdfa38f59
> fix: horizontal scroll

- crates/context_aware_config/src/api/context/helpers.rs
- crates/context_aware_config/src/api/context/types.rs
- crates/context_aware_config/src/api/functions/handlers.rs
- crates/context_aware_config/src/api/functions/helpers.rs
- crates/context_aware_config/src/validation_functions.rs
> fix: function fetch with type

- crates/frontend/src/providers/alert_provider.rs
> fix: executing set_timeout only on wasm32 targets

- clients/haskell/hs-cac-client/hs-cac-client.cabal
- clients/haskell/hs-cac-client/src/Client.hs
- clients/haskell/hs-cac-client/src/Main.hs
> feat: auto desearlizing resolved config

- crates/frontend/src/components/context_form.rs
- crates/frontend/src/components/context_form/utils.rs
- crates/frontend/src/components/dimension_form.rs
- crates/frontend/src/components/dimension_form/types.rs
- crates/frontend/src/components/dropdown.rs
- crates/frontend/src/logic.rs
- crates/frontend/src/pages/context_override.rs
- crates/frontend/src/pages/dimensions.rs
- crates/frontend/src/pages/experiment_list.rs
- crates/superposition_types/src/database/models/cac.rs
- crates/superposition_types/src/database/types.rs
UI Changes for dependent dimensions
Add the dependent dimensions in the context_form while adding the dimensions in the context.
https://github.com/user-attachments/assets/024096ac-50d5-4290-b0be-94c018926ae5
> feat: dependent dimensions ui

- docker-compose/postgres/db_init.sql
- workspace_template.sql
> fix: workspace_template.sql and db-init.sql

- clients/tests/ts/tests/default_config.test.ts
added default-config endpoint tests
> test: added default-config endpoint tests

- clients/generated/smithy/ts/src/commands/BulkOperationCommand.ts
- clients/generated/smithy/ts/src/models/models_0.ts
- clients/generated/smithy/ts/src/protocols/Aws_restJson1.ts
- clients/tests/ts/tests/context.test.ts
- clients/tests/ts/tests/default_config.test.ts
- crates/context_aware_config/src/api/context/operations.rs
- makefile
- smithy/models/context.smithy
- ✅  Tests for contexts (list and delete endpoint tests are pending)
- ✅  Fixed buggy mandatory dimension check in move operation
- ✅  Fixed type-mismatch for bulk operation payload between smithy and backend (context field wrongly names condition)
- ✅  Incase of move operation, description was being updated in the context conflict flow, so without a conflict the moved context never had the updated description
- ⚠️  Not updating change_reason in a move operation (to be fixed)
- ⚠️  Payload type Mismatch for Move operation in Bulk API (to be fixed) [Will fail bulk operation made by client having a move operation]
> fix: added tests for contexts (along with bug-fixes)

- clients/tests/ts/tests/context.test.ts
- clients/tests/ts/tests/default_config.test.ts
> test: added cleanup step for tests

- clients/tests/ts/tests/experiments.test.ts
- makefile
> test: Update experiments test cleanup

- crates/frontend/src/pages/config_version_list.rs
- crates/frontend/src/pages/context_override.rs
- crates/frontend/src/pages/default_config.rs
- crates/frontend/src/pages/dimensions.rs
- crates/frontend/src/pages/experiment_list.rs
- crates/frontend/src/pages/function/function_list.rs
- crates/frontend/src/pages/workspace.rs
Pagination params of each page are not tracked in the url of the pages
Added pagination params support to frontend urls
> feat: Add Pagination Params to frontend url

- clients/generated/smithy/ts/src/commands/UpdateDimensionCommand.ts
- clients/generated/smithy/ts/src/models/models_0.ts
- clients/generated/smithy/ts/src/protocols/Aws_restJson1.ts
- clients/tests/ts/tests/context.test.ts
- crates/context_aware_config/src/api/context/handlers.rs
- crates/experimentation_platform/src/api/experiments/handlers.rs
- crates/frontend/src/pages/experiment_list.rs
- crates/superposition_types/src/api/experiments.rs
- crates/superposition_types/src/database/models/experimentation.rs
- crates/superposition_types/src/lib.rs
- smithy/models/dimension.smithy
> fix: Update experiment restrictions and default value of sort_by

- crates/frontend/src/pages/context_override.rs
- crates/frontend/src/pages/default_config.rs
- crates/frontend/src/pages/experiment_list.rs
- crates/frontend/src/pages/workspace.rs
- crates/superposition_types/src/custom_query.rs
1. page reseting is not happening correctly
2. prefix filter is getting removed from path
1. fix logic for page reseting
2. temporary fix - disable param auto updater for default-config
> fix: Page reset issue in frontend

- .github/workflows/ci_check_pr.yaml
- .github/workflows/docker_image_gen.yaml
- .github/workflows/example_docker_image_gen.yaml
Slow builds for docker and rust
setup multi-platform builds for docker and use rust-cache for rust
> chore: improve builds

- clients/tests/ts/tests/context.test.ts
- crates/context_aware_config/src/api/context/helpers.rs
- crates/context_aware_config/src/api/default_config/handlers.rs
- crates/context_aware_config/src/api/default_config/types.rs
- crates/context_aware_config/src/api/dimension/handlers.rs
- crates/context_aware_config/src/api/dimension/types.rs
- crates/context_aware_config/src/api/functions/handlers.rs
- crates/context_aware_config/src/api/functions/helpers.rs
- crates/context_aware_config/src/validation_functions.rs
- crates/frontend/src/api.rs
- crates/frontend/src/components/default_config_form.rs
- crates/frontend/src/components/dimension_form.rs
- crates/frontend/src/components/dimension_form/types.rs
- crates/frontend/src/components/function_form.rs
- crates/frontend/src/components/function_form/types.rs
- crates/frontend/src/components/function_form/utils.rs
- crates/frontend/src/pages/dimensions.rs
- crates/frontend/src/pages/function.rs
- crates/frontend/src/pages/function/function_list.rs
- crates/superposition_types/migrations/2025-03-09-124604_dependent_dimensions/up.sql
- crates/superposition_types/migrations/2025-04-07-101100_linking_autocomplete_functions/down.sql
- crates/superposition_types/migrations/2025-04-07-101100_linking_autocomplete_functions/up.sql
- crates/superposition_types/src/api/functions.rs
- crates/superposition_types/src/database/diesel.toml
- crates/superposition_types/src/database/models/cac.rs
- crates/superposition_types/src/database/schema.rs
- crates/superposition_types/src/database/types.rs
- docker-compose/postgres/db_init.sql
- workspace_template.sql
No one is reviewing my PR because it is 
Break up the PR, this is the first commit. Reference #458 for the complete picture
> feat: add support to link autocomplete functions to dimensions

- clients/generated/smithy/ts/src/commands/CreateWorkspaceCommand.ts
- clients/generated/smithy/ts/src/commands/ListWorkspaceCommand.ts
- clients/generated/smithy/ts/src/commands/UpdateWorkspaceCommand.ts
- clients/generated/smithy/ts/src/models/models_0.ts
- clients/generated/smithy/ts/src/protocols/Aws_restJson1.ts
- clients/tests/ts/index.ts
- clients/tests/ts/tests/workspace.test.ts
- crates/context_aware_config/src/api/context/helpers.rs
- crates/context_aware_config/src/api/context/operations.rs
- crates/frontend/src/components/experiment_form.rs
- crates/frontend/src/components/side_nav.rs
- crates/frontend/src/components/workspace_form.rs
- crates/frontend/src/hoc/layout.rs
- crates/frontend/src/pages/context_override.rs
- crates/frontend/src/pages/experiment_list.rs
- crates/frontend/src/pages/organisations.rs
- crates/frontend/src/pages/workspace.rs
- crates/superposition/src/workspace/handlers.rs
- crates/superposition_types/migrations/2025-04-17-053400_limiting_operators/down.sql
- crates/superposition_types/migrations/2025-04-17-053400_limiting_operators/up.sql
- crates/superposition_types/src/api/workspace.rs
- crates/superposition_types/src/database/models.rs
- crates/superposition_types/src/database/superposition_schema.rs
- docker-compose/postgres/db_init.sql
- postman/superposition/Workspace/Create/request.json
- smithy/models/workspace.smithy
Non deterministic resolutions of configs
Create a workspace setting called strict mode that limits operators to `==`
https://github.com/user-attachments/assets/b7dfbcef-0d31-495d-9127-5f33c25ab716
> feat: add strict mode support for workspaces

- clients/generated/smithy/typescript/src/commands/BulkOperationCommand.ts
- clients/generated/smithy/typescript/src/commands/UpdateOverrideCommand.ts
- clients/generated/smithy/typescript/src/models/models_0.ts
- clients/generated/smithy/typescript/src/protocols/Aws_restJson1.ts
- clients/tests/typescript/tests/context.test.ts
- crates/context_aware_config/src/api/config/handlers.rs
- crates/context_aware_config/src/api/context.rs
- crates/context_aware_config/src/api/context/handlers.rs
- crates/context_aware_config/src/api/context/helpers.rs
- crates/context_aware_config/src/api/context/operations.rs
- crates/context_aware_config/src/api/context/types.rs
- crates/experimentation_platform/src/api/experiments/handlers.rs
- crates/experimentation_platform/src/api/experiments/types.rs
- crates/frontend/src/components/context_form/utils.rs
- crates/frontend/src/pages/context_override.rs
- crates/frontend/src/providers/alert_provider.rs
- crates/superposition_types/src/api/context.rs
- crates/superposition_types/src/database/models.rs
- smithy/models/context.smithy
> feat: Update override using context id

- crates/frontend/src/api.rs
- crates/frontend/src/app.rs
- crates/frontend/src/components.rs
- crates/frontend/src/components/badge.rs
- crates/frontend/src/components/dropdown.rs
- crates/frontend/src/components/input.rs
- crates/frontend/src/components/side_nav.rs
- crates/frontend/src/components/webhook_form.rs
- crates/frontend/src/pages.rs
- crates/frontend/src/pages/webhooks.rs
- crates/frontend/src/types.rs
- crates/superposition_types/src/api/webhook.rs
- crates/superposition_types/src/database/models.rs
- crates/superposition_types/src/database/models/others.rs
https://github.com/user-attachments/assets/2879f8d8-d707-4492-bceb-58f59be902f1
> feat: webhooks ui

- .gitignore
- crates/frontend/src/api.rs
- crates/frontend/src/app.rs
- crates/frontend/src/components/experiment.rs
- crates/frontend/src/components/side_nav.rs
- crates/frontend/src/components/table.rs
- crates/frontend/src/components/table/types.rs
- crates/frontend/src/logic.rs
- crates/frontend/src/pages.rs
- crates/frontend/src/pages/compare_overrides.rs
- crates/frontend/src/pages/config_version_list.rs
- crates/frontend/src/pages/custom_types.rs
- crates/frontend/src/pages/default_config.rs
- crates/frontend/src/pages/dimensions.rs
- crates/frontend/src/pages/experiment_list/utils.rs
- crates/frontend/src/pages/function/utils.rs
- crates/frontend/src/pages/home.rs
- crates/frontend/src/pages/organisations.rs
- crates/frontend/src/pages/webhooks.rs
- crates/frontend/src/pages/workspace.rs
It is difficult to view differences between multiple contexts and compare them
Introduce a compare UI to see diffs
https://github.com/user-attachments/assets/fa616921-abac-4235-9c8a-5487e76cc64f
> feat: introduce compare UI

- crates/service_utils/src/helpers.rs
- crates/superposition/src/app_state.rs
> fix: custom headers parsing for webhook

- crates/superposition_types/src/api/experiments.rs
- crates/superposition_types/src/custom_query.rs
> fix: Removing completed and discarded experiments from experiment home page

- crates/superposition_types/migrations/2025-05-16-082925_experiment_groups/down.sql
- crates/superposition_types/migrations/2025-05-16-082925_experiment_groups/up.sql
- crates/superposition_types/src/database/models/experimentation.rs
- crates/superposition_types/src/database/schema.rs
- docker-compose/postgres/db_init.sql
- workspace_template.sql
Isolate experiments from each other in experiment groups
First PR for experiment groups
> feat: introduce experiment groups data model

- crates/frontend/src/components/context_card.rs
- crates/frontend/src/components/experiment_conclude_form.rs
> fix: Fix UI issues

- crates/frontend/src/pages/default_config.rs
- crates/frontend/src/pages/dimensions.rs
Use of default in place where there should not be any default and then wrapping it in some type
Remove incorrect usage of defaults
> fix: Function name prefill issue

- crates/experimentation_platform/src/api/experiments/handlers.rs
List all experiments, disregard the provided filters
Obey filters for list all experiments
> fix: List exp behaviour for list all

- crates/frontend/Cargo.toml
- crates/frontend/src/pages/context_override.rs
- crates/frontend/src/pages/context_override/filter.rs
- crates/superposition_types/src/custom_query.rs
> fix: Show context filters

- crates/context_aware_config/src/api/config/handlers.rs
Currently we get_config and get_resolved_config api accepts version as query params , also api handler checks if 
version is being set at the workspace level , so if any version set at workspace level then there isn't a way to get the latest config .
Query params for the above to api will now accept "latest" as version param , based on which the latest config will be served
> fix: latest support in config params

- clients/tests/typescript/tests/context.test.ts
- clients/tests/typescript/tests/experiments.test.ts
- crates/context_aware_config/src/api/context/types.rs
- crates/experimentation_platform/src/api/experiments/helpers.rs
- crates/experimentation_platform/tests/experimentation_tests.rs
- crates/superposition_types/src/config.rs
> fix: added validation for and wrapper over context json logic

- clients/openfeature/python/cac_client.py
- clients/openfeature/python/provider.py
- clients/openfeature/python/test.py
> fix: python update

- clients/tests/typescript/tests/experiment_groups.test.ts
- crates/experimentation_platform/src/api/experiment_groups/helpers.rs
- crates/frontend/src/api.rs
- crates/frontend/src/app.rs
- crates/frontend/src/components.rs
- crates/frontend/src/components/delete_modal.rs
- crates/frontend/src/components/experiment_form.rs
- crates/frontend/src/components/experiment_group_form.rs
- crates/frontend/src/components/side_nav.rs
- crates/frontend/src/pages.rs
- crates/frontend/src/pages/experiment_group_listing.rs
- crates/frontend/src/pages/experiment_groups.rs
- crates/superposition_types/src/api/experiment_groups.rs
- crates/superposition_types/src/database/models/experimentation.rs
continuation of #508 
Add a UI for experiment groups
https://github.com/user-attachments/assets/ddb1a413-10fc-4742-a560-02dfd085a805
> feat: added a CRUD for experiment groups

- crates/core/src/experiment.rs
- crates/core/src/ffi.rs
- crates/core/src/ffi_legacy.rs
- crates/core/src/lib.rs
- crates/superposition_types/src/database/models/experimentation.rs
added experimentation logic and niffi
> feat: add exp core

- Cargo.lock
- crates/core/Cargo.toml
- crates/core/src/experiment.rs
- crates/core/src/ffi.rs
Updated (uni)ffi interfaces w/ experimentation support.
> feat: Experimentation UniFFI

- crates/superposition_types/migrations/2025-07-02-175438_experiment_groups_audit/down.sql
- crates/superposition_types/migrations/2025-07-02-175438_experiment_groups_audit/up.sql
- docker-compose/postgres/db_init.sql
- workspace_template.sql
> chore: Add missing audit log for experiment group table

- crates/experimentation_client/src/lib.rs
Remove from & to date filter , as we will always fetch the active experiments
> fix: exp client

- crates/frontend/src/components/side_nav.rs
- crates/frontend/src/pages/workspace.rs
> fix: Redirect url behaviour with prefix

- docs/docusaurus.config.ts
> fix: change base URL for docusaurus

- makefile
- smithy/patches/java.patch
- smithy/smithy-build.json
> fix: smithy build

- superposition.sql
> chore: Add superposition.sql for initial db setup

- .github/workflows/release.yaml
- docs/docusaurus.config.ts
Cannot search through our docs
Add algolia search to docusaurus
THE API KEY IS SAFE TO COMMIT
https://docusaurus.io/docs/search#connecting-algolia
> feat: Algolia support

- crates/context_aware_config/Cargo.toml
- crates/experimentation_platform/Cargo.toml
- crates/frontend/Cargo.toml
- crates/superposition/Cargo.toml
- crates/superposition_types/Cargo.toml
> fix: Use workspace superposition_types in frontend crate

- crates/experimentation_client/src/lib.rs
> fix: bucketing logic

- smithy/patches/java.patch
> fix: Java.patch file

- crates/superposition_types/src/api.rs
- crates/superposition_types/src/api/workspace.rs
> fix: Make auto populate control backwards compatible

- docs/docs/api/Superposition.openapi.json
- docs/docusaurus.config.ts
- makefile
The openapi spec generated from Smithy is not committed and doc generation fails.
https://github.com/juspay/superposition/actions/runs/17551148409/job/49843680518
Commit it.
NA
NA
NA
NA
NA
> docs: commit smithy generated openapi spec

- docs/docusaurus.config.ts
docs are broken
revert the routeBasePath change
NA
NA
NA
NA
NA
> docs: revert routeBasePath change

- docker-compose.yaml
- makefile
> chore: Remove localstack as a mandatory requirement for local setup

- .github/workflows/release.yaml
> fix: Create release step

- clients/haskell/hs-exp-client/src/Client.hs
- clients/haskell/hs-exp-client/src/Main.hs
- clients/java/bindings/src/main/kotlin/uniffi/superposition_client/superposition_client.kt
- clients/java/openfeature-provider/src/main/java/io/juspay/superposition/openfeature/SuperpositionOpenFeatureProvider.java
- clients/java/openfeature-provider/src/main/kotlin/io/juspay/superposition/openfeature/EvaluationArgs.kt
- clients/javascript/bindings/native-resolver.ts
- clients/python/bindings/superposition_bindings/superposition_client.py
- clients/python/provider/superposition_provider/configuration_client.py
- crates/experimentation_client/src/interface.rs
- crates/experimentation_client/src/lib.rs
- crates/experimentation_platform/src/api/experiments/handlers.rs
- crates/superposition_core/src/experiment.rs
- crates/superposition_core/src/ffi.rs
- crates/superposition_core/src/ffi_legacy.rs
- crates/superposition_provider/src/client.rs
- crates/superposition_provider/src/provider.rs
- crates/superposition_types/src/api/experiments.rs
- examples/experimentation_client_integration_example/src/main.rs
- headers/libexperimentation_client.h
> fix: cohort resolution in get applicable variants

- crates/context_aware_config/src/api/config/handlers.rs
> fix: added change reason fallback
