.env.example, .github/CODEOWNERS, .github/PULL_REQUEST_TEMPLATE.md, .github/workflows/ci_check_pr.yaml, .github/workflows/ci_merge_main.yaml, crates/frontend/src/types.rs, crates/service_utils/src/db/utils.rs, crates/service_utils/src/service/types.rs, docker-compose.yaml, docker-compose/localstack/get_db_password.sh, makefile
Superposition doesn't have testing for every PR setup
add that using github actions
=> chore: add PR testing workflows

crates/frontend/src/components/default_config_form/default_config_form.rs, crates/frontend/src/components/dimension_form/dimension_form.rs, crates/frontend/src/components/override_form/override_form.rs, crates/frontend/src/pages/Home/Home.rs, crates/frontend/src/pages/default_config/default_config.rs, crates/frontend/src/pages/experiment_list/experiment_list.rs, crates/superposition/src/main.rs
Resolve page doesn't resolve when the type of a value is not a string because  the code was trying convert everything to string.
Properly parse types and display them so that the resolve UI works correctly. Also replace `<input>` for values in some places with `textarea`
=> fix: resolve page failing when any type other than string is used for a value

crates/frontend/src/pages/default_config/default_config.rs, crates/frontend/src/utils.rs
Grouped config keys were not sorted as per folders and keys.
Sorted it based on folder and keys
Before
After
=> fix: sorted grouped config keys

README.md, docs/context-aware-config.md, docs/experimentation.md
This PR updates the docs to simplify some wording, use the same example as the proposed demo-app and makes both experimentation/cac docs refer to the same example.  It also links to the Postman collection as a substitute for API documentation
Same as above
NA
NA
NA
NA
NA
=> docs: update README/experimentation/cac docs

.github/workflows/ci_check_pr.yaml, crates/service_utils/src/db/utils.rs, docs/setup.md, flake.nix, makefile
The local setup of superposition depends on nix with may impede some users from trying it out
Provide an alternate way to use superposition without setting up nix
=> fix: setup superposition without nix

makefile, scripts/create-tenant.sh
The create-tenant script leaves behind `.sql` files that were used to create the tenant schemas - leaving a dirty repository state.
This fix removes the temporarily generated sql files and prints the generated sql file in case there is an error.  The script also supports a -k argument that allows one to keep the generated .sql files so as to use it in another environment and delete it manually later.
NA
NA
NA
NA
NA
=> chore: clean-up sql files post tenant creation

crates/frontend/src/components/condition_pills/condition_pills.rs, crates/frontend/src/components/condition_pills/types.rs, crates/frontend/src/components/condition_pills/utils.rs, crates/frontend/src/components/context_form/context_form.rs, crates/frontend/src/components/default_config_form/default_config_form.rs, crates/frontend/src/components/drawer/drawer.rs, crates/frontend/src/components/experiment/experiment.rs, crates/frontend/src/components/override_form/override_form.rs, crates/frontend/src/pages/ContextOverride/context_override.rs, crates/frontend/src/pages/Home/Home.rs, crates/frontend/src/pages/experiment_list/utils.rs
We had inconsistent parsing logic for context, which led to wrong data display of context.
Fix the parsing logic
=> fix: fixed condition parsing and display

crates/experimentation_client/src/interface.rs, crates/experimentation_client/src/lib.rs, crates/experimentation_client/src/utils/mod.rs
Filter prefix from experiments.
Added Filter prefix support in experimentation client.
=> feat: filter support in experimentation client

crates/context_aware_config/src/api/context/helpers.rs, crates/context_aware_config/src/validation_functions.rs, crates/experimentation_platform/src/api/experiments/handlers.rs, crates/experimentation_platform/src/api/experiments/helpers.rs, crates/experimentation_platform/tests/experimentation_tests.rs, crates/frontend/src/components/context_form/context_form.rs, crates/frontend/src/components/function_form/function_form.rs, crates/frontend/src/pages/ContextOverride/context_override.rs, crates/frontend/src/pages/Experiment/mod.rs, crates/frontend/src/pages/experiment_list/experiment_list.rs, crates/frontend/src/pages/function/function.rs, crates/frontend/src/utils.rs, crates/service_utils/src/helpers.rs
`variantIds` dimension, which is specific for experimentation-platform use, can be passed in the context when creating experiments.
- validating experiment contexts to not have `variantIds` as dimensions
- excluded `variantIds` from the dropdown in create experiment and create context form
=> fix: reject experiment contexts with `variantIds`

crates/superposition/src/main.rs
Api response are getting cached on the client side, which gives inconsistent results
Add cache-control: no-store headers , so that response should not cached in private and shared cache
NA
NA
NA
NA
=> add cache control headers for all routes

crates/context_aware_config/src/api/config/handlers.rs, crates/context_aware_config/src/api/context/handlers.rs, crates/context_aware_config/src/api/context/mod.rs
Too many Context duplicates, where some contexts are a subContext of other one's with the same overrides, so the parent one is not even required 
Removing contexts if we find any one subcontext with the same override key, then we remove the override key from the parent context, now if all of the override keys are removed from the parent context then we can remove the entire context, so we just delete it.
=> feat: reducing context tool

Cargo.lock, crates/experimentation_client/src/lib.rs, crates/experimentation_platform/src/api/experiments/handlers.rs, crates/experimentation_platform/src/api/experiments/helpers.rs, crates/frontend/src/components/context_form/utils.rs, crates/service_utils/Cargo.toml, crates/service_utils/src/helpers.rs
We were not able to create experiments and conclude them for default config, that is without giving any contexts
Made contexts optional, if it's None then we accept it as default config
DB schema has been changed for experiments table, made context as nullable before it was not null
=> fix: creating experiments for default-config (no context)

crates/frontend/src/components/pagination/pagination.rs, crates/frontend/src/components/table/table.rs, crates/frontend/src/components/table/types.rs, crates/frontend/src/pages/experiment_list/experiment_list.rs, crates/frontend/src/pages/function/function_list.rs
In paginated tables, the rows number was always from 1 upto the row count for the particular page. For example, if row count is 10 for each page, rows on 2nd page of the table too had sr number `1,2,3,..,10`, which should have been `11,12,..20`.
Move the pagination state inside the table, so that the row number can be calculated based on `current_page` and `count` of rows per page
=> fix: row numbering in paginated table

nix/pre-commit.nix
Even after adding separate rule for YAML files, eclint pre-commit hook is failing for yaml files containing array of objects
Disable eclint pre-commit hook
=> fix: Temporarily disable eclint

crates/frontend/src/api.rs, crates/frontend/src/components/alert/mod.rs, crates/frontend/src/components/context_form/utils.rs, crates/frontend/src/components/default_config_form/utils.rs, crates/frontend/src/components/dimension_form/utils.rs, crates/frontend/src/components/experiment_form/utils.rs, crates/frontend/src/components/function_form/utils.rs, crates/frontend/src/pages/default_config/default_config.rs, crates/frontend/src/utils.rs
No delete support for default config from UI
Add delete button for each row in default config table, which calls `DELETE /default-config/{key}` endpoint.
Refactored request function in `frontend/utils.rs` to return raw response instead of parsing it to a type.
Reason:
- Responses can be empty, not necessarily have a content.
- Parsing no-content to a type will always fail even if we are parsing it to `()` (unit), because `no-content` is not a valid JSON.
- Separating parsing of the response from the actual request part, will be bit cleaner, as request function will get bloated with conditionals to handle the `no-content` or any other scenario that I am not currently aware of.
=> feat: delete support for default config in UI

clients/haskell/hs-cac-client/src/Client.hs, clients/haskell/hs-exp-client/src/Client.hs, crates/cac_client/src/interface.rs, crates/experimentation_client/src/interface.rs, headers/libcac_client.h, headers/libexperimentation_client.h
When running client in jenkins it shows `multiple definition of `several client's functions as exp_client and cac_client' s functions had similar name.
Added prefix to the extern function for both cac and exp clients as `cac_` and `exp_` respectively.
=> fix: Add prefix to client's methods

crates/context_aware_config/diesel.toml, crates/experimentation_platform/src/schema.patch
while running make setup command, changes occurs in schema.rs file because schema.patch is not mentioned in diesel.toml
Added schema.patch file path in diesel.toml
NA
NA
NA
NA
=> fix: add patch_file in diesel.toml

crates/context_aware_config/src/api/context/handlers.rs, crates/context_aware_config/src/api/context/types.rs, crates/context_aware_config/src/api/functions/handlers.rs, crates/context_aware_config/src/api/functions/types.rs, crates/experimentation_client/src/lib.rs, crates/experimentation_client/src/types.rs
This PR addresses the `clippy::upper_case_acronyms` lint, which is enabled by default.
This PR updates the upper case enum variant names to use idiomatic `PascalCase` names, while ensuring that the API contract is unaffected. This is done by taking advantage of the [`#[serde(rename_all = "UPPERCASE")]`](https://serde.rs/container-attrs.html#rename_all) annotation.
I've added a unit test to verify that the contract was indeed unaffected, by running it before and after making the change. I can remove the unit test if the maintainers don't think it's required.
What ENVs need to be added or changed: N/A
Things needed to be done before deploying this change (if any): N/A
Things needed to be done after deploying this change (if any): N/A
| Endpoint        | Method           | Request body  | …
=> chore: rename upper case enum variants to use `PascalCase` names

crates/frontend/src/pages/experiment_list.rs
Experiment form had old values even after closing the drawer
re-render the experiment form with empty state, this can be easily done by changing value of `reset_exp_form` signal.
=> fix: reset experiment form after closing drawer

.github/workflows/nix.yaml
We are standardizing on using in-office NixOS/mac machines for running CI for Github repos.
=> Use self-hosted runners for Nix CI

Cargo.lock, Cargo.toml, clients/haskell/hs-cac-client/src/Client.hs, clients/haskell/hs-cac-client/src/Main.hs, clients/haskell/hs-exp-client/src/Client.hs, clients/haskell/hs-exp-client/src/Main.hs, crates/cac_client/src/interface.rs, crates/cac_client/src/lib.rs, crates/context_aware_config/Cargo.toml, crates/context_aware_config/src/api/config/handlers.rs, crates/context_aware_config/src/api/config/helpers.rs, crates/experimentation_client/src/interface.rs, crates/experimentation_client/src/lib.rs, headers/libcac_client.h, headers/libexperimentation_client.h
#117 
1. Filter currently works only for in operator with array and for all other types it checks direct equality
2. Experiment filtering was not doing actual filter, rather it was applying the entire context
3. Config prefix filtering was sent in context
4. Prefix filter param of expt filtering not exposed to hs-client
1. Use jsonlogic's partial_apply for config and experiment filtering
2. Add separate function for Experiment filtering just like the filter function for config - also exposed to hs-client.
3. Introduce separate param for prefix in config filtering.
4. Exposed prefix filter param of expt filtering to hs-client.
=> Use jsonlogic's partial_apply for config and experiment filtering

.gitignore, Cargo.lock, Cargo.toml, crates/cac_client/src/interface.rs, crates/cac_client/src/lib.rs, crates/experimentation_client/src/interface.rs, examples/cac_client_integration_example/Cargo.toml, examples/cac_client_integration_example/src/main.rs, examples/experimentation_client_integration_example/Cargo.toml, examples/experimentation_client_integration_example/src/main.rs
Clippy while analyzing CAC client shows a error for calling await on a MutexGuard. This happens when we use the standard library RwLock. 
Use tokio RwLock that handles this and is better at concurrent and parallel processing. Also add an integration example for cac client that lets implementers test out features of the client
=> Rework async library in CAC client

crates/frontend/src/components/override_form.rs
When you edit an override, the textarea sets the 'type' of values as String(value). On input in the field, the value is parsed to the correct type using the function `get_config_value`. Hence, if you are editing an input but leave the others as is, the submit request will fail because all types are sent as strings, even if they are not.
Parse the type at the time of submitting the form, not on ever input
=> fix: parse type when submitting overrides, not on input

crates/frontend/src/components/default_config_form.rs, crates/frontend/src/components/dimension_form.rs, crates/frontend/src/components/experiment_form.rs, crates/frontend/src/components/override_form.rs, crates/frontend/src/components/type_template_form.rs, crates/frontend/src/pages/context_override.rs
Inputs are not aligned in overrides form
Make these inputs aligned
=> fix: align inputs in override form

crates/context_aware_config/src/api/dimension/handlers.rs, crates/context_aware_config/src/api/dimension/types.rs, crates/frontend/src/components/dimension_form.rs, crates/frontend/src/components/dimension_form/types.rs, crates/frontend/src/pages/dimensions.rs
DB supports i32 values for priority but endpoints were restricted to u16
allow positive i32 number for dimension priority in dimension create
=> fix: allow positive i32 number for dimension priority in dimension create

crates/frontend/src/components.rs, crates/frontend/src/components/delete_modal.rs, crates/frontend/src/pages/context_override.rs
The Delete button in the override feature was deleting overrides immediately, without requesting user confirmation. This behavior poses a risk as these overrides are sensitive and critical.
Implemented a confirmation modal that appears when the Delete button is clicked. This modal prompts the user to confirm whether they really want to delete the override. The override will only be deleted if the user confirms by selecting "Yes."
Here is the screeshot for the UI Review :
=> feat: added delete override modal

crates/context_aware_config/src/api/config/handlers.rs, crates/experimentation_platform/src/api/experiments/handlers.rs
1. x-config-version not being sent in get config or resolve config if the request does not include any config-version
2. experiments wrongly tagging `version` as `tags`
fetch latest config version and return response from there if no config version is provided, if there are no snapshots, then fallback to default flow
=> fix: x-config-version in get config and experiments response

README.md, docs/creating-client.md
Lack of documentation on C libraries and Language integrations
Add that
=> chore: add more docs on integration with C libraries

crates/context_aware_config/src/api/config/handlers.rs
Stringified last_modified header 
parse it as rfc2822
NA
NA
NA
NA
=> fix: undo stringify of last_modified timestamp

crates/frontend/src/components.rs, crates/frontend/src/components/context_form.rs, crates/frontend/src/components/default_config_form.rs, crates/frontend/src/components/delete_modal.rs, crates/frontend/src/components/dimension_form.rs, crates/frontend/src/components/input_components.rs, crates/frontend/src/components/override_form.rs, crates/frontend/src/pages/context_override.rs, crates/frontend/src/utils.rs
Better form fields
- enum → Toggle
- boolean → dropdown with true and false options
https://github.com/user-attachments/assets/5152c2fb-316d-4617-86aa-09d90460ec8c
=> fix: Improve form inputs

crates/context_aware_config/src/api/context/handlers.rs
The only way to retrieve a context is by using its id
Add a new endpoint for getting context provided conditions in the body
The endpoint creates the hash out of the given condition, and performs a db lookup with the generated hash
| /context/get   | POST             | condition json | context object |
=> feat: Add fetch context from context condition

crates/context_aware_config/src/validation_functions.rs, crates/frontend/src/pages/function/function_create.rs
First process was allowed in js_function sandbox environment
we need to enable env variables that is required for js_functions only
Remove process from vm , delete all env variable keys except keys mentioned under `FUNCTION_ENV_VARIABLES`
NA
Add FUNCTION_ENV_VARIABLES and mention all env that is required for js_function
NA
NA
=> fix: remove process, filter env variables

nix/rust.nix
`.dylib` files contain information about their location. When the rust library is built using Nix, the build happens in a temporary build directory, which is removed after the build and once a corresponding `/nix/store/…` path is created. In the metadata of the `.dylib` files is the path to the temporary build directory, which needs to be patched.
This PR ensures the `.dylib` files are always searched for in the respective `/nix/store/...` path, instead of the temporary build directory.
=> fix(cac_client): Run `fixDarwinDylibNames` during `postInstall`

crates/context_aware_config/src/api/config/handlers.rs
when someone passes `?version=7224713864877502464` as the snapshot version the code currently fails to parse this is as a valid i64 version value and only accepts `?version="7224713864877502464"` as a correct input
Replace as_str conversion of version with as_i64
=> fix: Snapshot version parsing

clients/haskell/hs-cac-client/src/Client.hs, clients/haskell/hs-cac-client/src/Main.hs, docs/client-context-aware-configuration.md
haskell client doc
fixed haskell client doc
=> fix: haskell-client-doc

crates/frontend/src/pages/custom_types.rs, crates/frontend/src/types.rs
Panic in backend due to running wasm32-targeted code in non-wasm32 target
**Cause**
Invoking set_timeout function while SSR the page
**Source**
alert_provider::enqueue function, which invokes set_timeout
NOTE : Issue of running wasm32 target function on non-wasm32 targets should be handled separately in another PR
**Why alert_provider::enqueue is triggered?**
Mismatch in TypeTemplates struct on frontend and backend leading to failure in parsing type templates data.
Move all the types to a single crate, and reuse them across the workspace
Bring frontend type in-sync with the backend one.
=> fix: out-of-sync TemplateType struct

clients/python/Readme.md, clients/python/cacclient/__init__.py, clients/python/cacclient/client.py, clients/python/expclient/__init__.py, clients/python/expclient/client.py, clients/python/main.py
=> feat: adding python cac and experimentation client wrapper

Cargo.lock, Cargo.toml, crates/context_aware_config/Cargo.toml, crates/service_utils/Cargo.toml, crates/service_utils/src/aws/kms.rs, crates/service_utils/src/db/utils.rs, crates/service_utils/src/lib.rs, crates/superposition/Cargo.toml
we are using aws kms to store secrets like db password and when we are deploying superposition service to different region aws kms needs which region to call to decrypt those keys for that the library we were using was rusto which has a map for the regions but when we tried to deployed in sp-south-2 region it failed because the map does not contain that region.
solution is from rusto we moved to different library aws-sdk-kms that handles it.
No env change
Describe any possible issues …
=> fix: changing aws kms library to aws-sdk-kms to rusto

crates/context_aware_config/src/api/default_config/handlers.rs
Most APIs return the entity object created, but this is not done for default config
return the row that was created/updated in the database
Solves #189
=> fix: return default config object when created

.github/workflows/nix.yaml
Use https://omnix.page/om/ci.html to build Nix outputs.
`omnix` is now installed in self-hosted runners.
=> chore(nix): Switch to omnix

crates/frontend/src/pages/context_override.rs
In case of empty overrides list , page does not have any prompt text to hint user
Added prompt text in case of empty page
=> fix: empty-override-prompt-text

.github/workflows/docker_image_gen.yaml, .github/workflows/example_docker_image_gen.yaml, DockerFile, example.DockerFile
Building amd64 and arm64 images takes a long time (6h) on the free github runners account. 
For now, separate out the build actions
=> Update github actions

crates/context_aware_config/src/api/dimension/handlers.rs, crates/context_aware_config/src/api/dimension/types.rs, crates/context_aware_config/src/api/dimension/utils.rs, crates/frontend/src/api.rs, crates/frontend/src/pages/dimensions.rs, crates/frontend/src/utils.rs, postman/cac.postman_collection.json, postman/cac/Dimension/.meta.json, postman/cac/Dimension/Delete Dimension/.event.meta.json, postman/cac/Dimension/Delete Dimension/event.prerequest.js, postman/cac/Dimension/Delete Dimension/event.test.js, postman/cac/Dimension/Delete Dimension/request.json
Implement delete dimension api
Implemented delete dimension api and ui , restricted to delete variantIds and also dimensions which are used in any contexts
NA
NA
=> feat: delete dimension api and ui

crates/superposition/src/main.rs, docker-compose.yaml, makefile
The size of the WebAssembly (WASM) file used in the application was too large, leading to increased loading times and potentially higher bandwidth usage.
To optimize the WASM file size, I used the Actix Web Compress middleware. This middleware automatically compresses the WASM file (and other static assets) using Brotli or Gzip compression, reducing the file size and improving loading times for users.
You need to update one ENV variable to run the docker image locally : 
`DB_HOST = host.docker.internal:5432`
Otherwise , No new environment variables are required for this change.
Monitor the application’s performance to ensure the compression is working as expected and that there are no issues with asset delivery.
No changes to the API endpoints.
=> fix: optimised wasm file size

crates/frontend/src/components/condition_pills.rs, crates/frontend/src/components/context_card.rs, crates/frontend/src/components/experiment.rs, crates/frontend/src/components/table.rs, crates/frontend/src/hoc/layout.rs, crates/frontend/src/pages/context_override.rs, crates/frontend/src/pages/custom_types.rs, crates/frontend/src/pages/default_config.rs, crates/frontend/src/pages/dimensions.rs, crates/frontend/src/pages/experiment_list.rs, crates/frontend/src/pages/function/function_list.rs, crates/frontend/src/pages/home.rs, crates/frontend/src/providers.rs, crates/frontend/src/providers/condition_collapse_provider.rs, crates/frontend/styles/tailwind.css
Conditions on Overrides and Resolve page overflowed the screen width forcing to horizontally scroll to check the content.
Default view - content is truncated
Expanded view - on clicking the pills it will expanded to show the wrapped content.
=> fix: horizontal scroll for big conditions

crates/frontend/src/components/button.rs, crates/frontend/src/components/default_config_form.rs, crates/frontend/src/components/dimension_form.rs, crates/frontend/src/components/experiment_form.rs, crates/frontend/src/components/experiment_ramp_form.rs, crates/frontend/src/components/function_form.rs, crates/frontend/src/components/type_template_form.rs, crates/frontend/src/pages/context_override.rs, crates/frontend/src/pages/home.rs
There is no indication of an event happening when forms are submitted
Provide a loader and disable the button on click of the submit button
closes #14 
https://github.com/user-attachments/assets/f901ac52-416c-483e-8db1-faa110bb3779
=> feat: add button loader when network requests are in progress

crates/frontend/src/api.rs, crates/frontend/src/pages/experiment.rs, crates/frontend/src/types.rs
Single Experiment page generation failed with error `Error fetching experiment`.
This happened because the API response was expected to be of  `Experiment` type which had `context` as `Vec<Conditions>` wasn't able to de-serialize correctly.
The correct expected API response type should have been `ExperimentResponse`, which we overlooked.
- Change `fetch_experiment` return value to `ExperimentResponse`
- implemented `From<ExperimentResponse>` for `Experiment`
=> fix: using ExperimentResponse type for single experiment get response

crates/frontend/src/components/condition_pills/types.rs
In case of the override clone event, the changes made to the context value doesn't reflect in `create` request payload.
- With an existing context data, operands contains `{"var": <dimension_name>}` we are filtering out this entry from the operands while constructing the form.
- But on input, to update the value, the original context which contains `{"var": <dimension_name>}` is being used.
- There is difference in position where the value should be updated before and after the filtering out `var`.
- The on:input handler prevents this update when the entry at the given certain index is `var`.
Result => The new/updated value is disposed of.
As a temporary solution we can remove the `var` from the list of operands at the initial state.
=> fix: temp fix for override clone operation

Cargo.lock, crates/experimentation_platform/Cargo.toml, crates/experimentation_platform/src/api/experiments/handlers.rs, crates/experimentation_platform/src/api/experiments/helpers.rs, crates/experimentation_platform/src/api/experiments/types.rs
get_applicable_variants only exist as a functionality inside client
Add get_applicable_variants as  an endpoint in experimentation
| /experiments/applicable_variants      | POST | {context: Value, toss: i8} | Vec<Variants> |
Code duplication
=> feat: Add get_applicable_variants as expt endpoint

.vscode/settings.json
Tailwind extension fails to show the value of the tailwind classes on hover
Add tailwind extension settings to workspace settings for vscode
=> chore: Add tailwind extension settings to workspace settings for vscode

Dockerfile, crates/frontend/src/api.rs, crates/frontend/src/components/default_config_form.rs, crates/frontend/src/components/experiment_ramp_form.rs, crates/frontend/src/components/side_nav.rs, crates/frontend/src/hoc/layout.rs, crates/frontend/src/pages/context_override.rs, crates/frontend/src/pages/default_config.rs, crates/frontend/src/pages/experiment.rs, crates/frontend/src/pages/experiment_list.rs, crates/frontend/src/pages/home.rs, example.Dockerfile, rust-toolchain.toml
1. `dlmalloc` failing in FE after upgrading to rust 1.78.0
2. unhandled warnings use of signals in non-reactive sections
3. content mismatch issue while using key grouping
4. range for ramp is allowed till 100
1. Revert back to rust 1.76.0
2. convert `get` to `get_untracked` and other similar fixes (might not have solved all)
3. move the check of local storage value to a `create_effect` to avoid initial value mismatch between client and SSR
4. limit the max value of ramp based on the allowed max value
=> fix: Frontend related issues and warnings

crates/frontend/src/components/dropdown.rs
Case sensitive dropdown search in UI
transforming search term and option labels to lowercase before matching
=> fix: case-insensitive dropdown search

Cargo.lock, Cargo.toml, crates/cac_client/Cargo.toml, crates/cac_client/src/lib.rs, crates/cac_toml/src/bin.rs, crates/cac_toml/src/lib.rs, crates/context_aware_config/Cargo.toml, crates/context_aware_config/src/lib.rs, crates/experimentation_client/Cargo.toml, crates/experimentation_client/src/lib.rs, crates/experimentation_platform/Cargo.toml, crates/experimentation_platform/src/lib.rs, crates/frontend/Cargo.toml, crates/frontend/src/lib.rs, crates/service_utils/Cargo.toml, crates/service_utils/src/lib.rs, crates/superposition/Cargo.toml, crates/superposition/src/main.rs, crates/superposition_macros/Cargo.toml, crates/superposition_macros/src/lib.rs, crates/superposition_types/Cargo.toml, crates/superposition_types/src/lib.rs, examples/cac_client_integration_example/Cargo.toml, examples/cac_client_integration_example/src/main.rs, examples/cac_toml_app_example/src/main.rs, examples/experimentation_client_integration_example/Cargo.toml, examples/experimentation_client_integration_example/src/main.rs, examples/superposition-demo-app/Cargo.toml, examples/superposition-demo-app/src/main.rs, makefile
1. `make run` compiles code twice
2. Redundant dependencies across all crates
3. Single use dependency specified at workspace `Cargo.toml`
4. `superposition_types` uses `diesel` as dependency, which causes dependency issues in 3rd party repos using this crate
5. dependencies in random order
6. `cac_client` returning data of types `superposition_types::result::Result<T>` in cases where the return should neither be a `Result` type or can simply be a `Result<T, String>`
1. Remove redundant compile step
2. Remove unused dependencies, mandate `#![deny(unused_crate_dependencies)]` for all crates
3. Localise single use dependency to the crates instead of workspace `Cargo.toml`
4. make `result` type as a feature for `superposition_types` (make `diesel` optional)
5. sorted dependencies in …
=> Dependency pruning

crates/context_aware_config/src/api/context/handlers.rs, crates/context_aware_config/src/api/default_config/handlers.rs, crates/context_aware_config/src/api/dimension/handlers.rs, crates/context_aware_config/src/api/functions/handlers.rs, crates/experimentation_platform/src/api/experiments/handlers.rs, crates/superposition_types/src/lib.rs
`SuperpositionUser` trait was introduced as a means to provide a way to convert any other user type to `superposition_types::User` type, which is not needed as the correct way around this is implement `superposition_types::User: From<Self>` for the other User type
Deleted `SuperpositionUser` trait and its usages
=> chore: Delete SuperpositionUser trait

crates/superposition_types/src/custom_query.rs, crates/superposition_types/src/lib.rs
In current implementation for filtering config/other resources using query params, variables such as   
- config version (version), merge strategy(merge_strategy), etc that are platform specific as passed along with the 
- filters for dimensions  (<dimension_name>=<dimension_value>)
Since dimension names are user-defined there are chances of conflict between dimension names and platform specific params.
Namespacing platform specific params with prefixes such as `platform` can be one of the way to resolve the conflict between platform params and dimension names.
There are multiple ways of namespacing query params with `platform`:
- `platform_<param name>`
- `platform.<param name>`
- `platform[<param name>]`
Since we allow use of `_` and `.` in names of dimensions and default config there …
=> feat: custom query-param extractor for platform queries

crates/frontend/src/api.rs, crates/frontend/src/app.rs, crates/frontend/src/components/button.rs, crates/frontend/src/components/condition_pills.rs, crates/frontend/src/components/context_card.rs, crates/frontend/src/components/dimension_form.rs, crates/frontend/src/components/experiment_form.rs, crates/frontend/src/components/experiment_ramp_form.rs, crates/frontend/src/components/function_form.rs, crates/frontend/src/components/input.rs, crates/frontend/src/components/side_nav.rs, crates/frontend/src/components/table.rs, crates/frontend/src/components/type_template_form.rs, crates/frontend/src/pages.rs, crates/frontend/src/pages/config_version.rs, crates/frontend/src/pages/config_version_list.rs, crates/frontend/src/pages/context_override.rs, crates/frontend/src/pages/default_config.rs, crates/frontend/src/pages/dimensions.rs, crates/frontend/src/pages/experiment_list.rs, crates/frontend/src/pages/function.rs, crates/frontend/src/pages/home.rs, crates/frontend/src/types.rs
-  Added Snapshot UI List Page 
- Added Single Snapshot Page
=> feat: added snapshot_list and single view UI

Cargo.lock, crates/experimentation_platform/src/api/experiments/handlers.rs, crates/experimentation_platform/src/api/experiments/helpers.rs, crates/service_utils/src/helpers.rs, crates/service_utils/src/service/types.rs, crates/superposition/Cargo.toml, crates/superposition/Superposition.cac.toml, crates/superposition/src/app_state.rs, crates/superposition_macros/src/lib.rs, crates/superposition_types/src/lib.rs, crates/superposition_types/src/result.rs, crates/superposition_types/src/webhook.rs
Webhook trigger for experiments
Webhook trigger for experiments (Create, Conclude, ramp, update_overrides)
`experiments_webhook_config = { "value" = {}, "schema" = { "type" = "object", properties = {"url" = { "type" = "string" }, "method" = { "enum" = ["Post","Put","Get"], "type" = "string" },"headers" = { "type" = "array", "items" = { "type" = "string", "enum" = ["ConfigVersion"] }}, authorization = {"type" = "object", properties = { "key" = { "type" = "string" }, "value" = { "type" = "string" }}}, "required"= ["url", "method", "headers", "authorization"], "additionalProperties" = false}}}
`
Tenant Config Changes
=> feat: Webhook trigger for experiments

crates/frontend/src/components/default_config_form.rs, crates/frontend/src/components/dimension_form.rs, crates/frontend/src/components/input.rs, crates/frontend/src/components/override_form.rs, crates/frontend/src/components/type_template_form.rs, crates/frontend/src/pages/default_config.rs, crates/superposition_types/src/lib.rs, makefile
The input field to enter a type schema for a config was set to textarea
Use the smarter input component that we already use for overrides
https://github.com/user-attachments/assets/e187f0b2-7073-4e07-8932-5a60edfea1c2
=> feat: use new input type for json schema inputs as well

crates/experimentation_platform/src/api/experiments/handlers.rs, crates/service_utils/Cargo.toml, crates/service_utils/src/helpers.rs, crates/superposition/Superposition.cac.toml, crates/superposition_types/src/webhook.rs
Improvement in webhook event.
Added tenant_id, config_version in the webhook response.
And added custom_headers in webhook object too.
=> fix: fixed and improved webhooks

crates/frontend/src/components/default_config_form.rs, crates/frontend/src/components/input.rs, crates/frontend/src/utils.rs
The default config input selection was doing the same thing as Input component
Replace input with the new component to unify changes across frontend
P.S I used leptosfmt on default_config_form.rs only, so the diff may look large but most of them are formatting changes
=> refactor: make default config page's code cleaner

crates/context_aware_config/src/api/config/helpers.rs, crates/superposition_types/src/config.rs, crates/superposition_types/src/contextual.rs, crates/superposition_types/src/custom_query.rs, crates/superposition_types/src/overridden.rs
`Config.filter_by_prefix` gives wrong config on filtering
1. Fix the logic for `filter_by_prefix`
2. `try_filter_by_prefix` function was not needed, both server and client should use `filter_by_prefix`, using `try_filter_by_prefix` in server gives wrong output
3. Added tests for `Config`, `QueryMap`, `Contextual`, `Overridden` functions
=> fix: Filter config by prefix

crates/cac_client/src/lib.rs
After config change , client resolve fn gives wrong result , this is due to cache which is not getting invalidated 
when config changes
call invalidate function
=> invalidate client cache on config change

crates/context_aware_config/src/api/context/handlers.rs, crates/context_aware_config/src/api/context/types.rs, crates/superposition_types/src/custom_query.rs
`platform[key_name]` format for passing params forces to change all endpoints to create a consistency across all the endpoints
1. `dimension[dimension_name]` rather to get the dynamic dimension params from the query request and keep the other params outside of any prefix notation
2. split current `sort_by` filter into `sort_by` and `sort_on` filters, following the new convention
=> feat: Use dimension[] for dimension params in context/list

crates/frontend/src/api.rs, crates/frontend/src/app.rs, crates/frontend/src/components/default_config_form/utils.rs, crates/frontend/src/components/experiment_conclude_form/utils.rs, crates/frontend/src/components/function_form/utils.rs, crates/frontend/src/components/workspace_form.rs, crates/frontend/src/pages/context_override.rs, crates/frontend/src/pages/custom_types.rs, crates/frontend/src/pages/function.rs, crates/frontend/src/pages/function/function_create.rs, crates/frontend/src/pages/organisations.rs, crates/service_utils/src/middlewares/tenant.rs, crates/service_utils/src/service/types.rs, crates/superposition/src/auth.rs, crates/superposition/src/auth/authenticator.rs, crates/superposition/src/auth/no_auth.rs, crates/superposition/src/auth/oidc.rs, crates/superposition/src/auth/oidc/types.rs, crates/superposition/src/auth/oidc/utils.rs, crates/superposition/src/main.rs
1. Updated Organisation selection page with table view
2. Added path prefix support for authentication routes
3. added authentication support for org_user after org has been selected
=> feat: auth path prefix support and org_user authentication

crates/context_aware_config/migrations/2024-12-05-172909_dimension_priority_default/down.sql, crates/context_aware_config/migrations/2024-12-05-172909_dimension_priority_default/up.sql
During position update statement , we increment/decrement the values , which conflicts with the unique constraint within the transaction
Making constraint as deferred which validates on transaction commit instead of statement
=> fix: add unique position contraint as deferred

crates/frontend/src/utils.rs
Webhook failures in frontend not handled properly
added a condition to ignore the 512 status code
=> fix: webhook ui failure handling

.env.example, crates/context_aware_config/src/api/audit_log/handlers.rs, crates/context_aware_config/src/api/config/handlers.rs, crates/context_aware_config/src/api/context/handlers.rs, crates/context_aware_config/src/api/context/helpers.rs, crates/context_aware_config/src/api/context/operations.rs, crates/context_aware_config/src/api/context/validations.rs, crates/context_aware_config/src/api/default_config/handlers.rs, crates/context_aware_config/src/api/dimension/handlers.rs, crates/context_aware_config/src/api/dimension/utils.rs, crates/context_aware_config/src/api/functions/handlers.rs, crates/context_aware_config/src/api/functions/helpers.rs, crates/context_aware_config/src/api/type_templates/handlers.rs, crates/context_aware_config/src/helpers.rs, crates/experimentation_platform/src/api/experiments/handlers.rs, crates/experimentation_platform/src/api/experiments/helpers.rs, crates/service_utils/src/extensions.rs, crates/service_utils/src/helpers.rs, crates/service_utils/src/lib.rs, crates/service_utils/src/middlewares/tenant.rs, crates/service_utils/src/service/types.rs, crates/superposition/src/app_state.rs, crates/superposition/src/auth/authenticator.rs, crates/superposition/src/auth/oidc.rs, crates/superposition_types/src/webhook.rs, docs/setup.md
Resolving the following issues
#353
#356  
#361
=> refactor: OrgId, WorkspaceId, SchemaName cleanup and refactor

crates/frontend/src/components/default_config_form.rs, crates/frontend/src/components/dimension_form.rs, crates/frontend/src/components/experiment.rs, crates/frontend/src/components/experiment_form.rs, crates/frontend/src/components/function_form.rs, crates/frontend/src/components/type_template_form.rs, crates/frontend/src/components/workspace_form.rs, crates/frontend/src/pages/context_override.rs
=> fix: Add success alerts and remove divider

Cargo.lock, crates/context_aware_config/src/helpers.rs
The variable schema_name is de-referenced only once, doing it twice grants access to the string it's wrapping
De-reference twice
=> fix: using schema_name in redis key

Cargo.lock, crates/frontend/Cargo.toml, crates/frontend/src/components/side_nav.rs
- Workspace dropdown shows only 10 entries
- The UI breaks due to https://github.com/rustwasm/wasm-pack/issues/1389
- Ask the API for all entries
- Update wasm-bindgen
Updating wasm-bindgen doesn't solve anything and the UI issue returns
=> fix: workspace dropdown and UI misalignment

crates/frontend/src/components/default_config_form.rs
The toggle component defaults to null instead of a boolean value when initially rendered, causing unexpected behavior until user interaction occurs.
Called the onChange event handler to properly handle the initial null state, ensuring the toggle always has a valid boolean value (true/false).
=> fix: toggle default value

crates/frontend/src/components/type_template_form.rs, crates/frontend/src/pages/custom_types.rs, crates/frontend/src/pages/default_config.rs
Delete modal is not displayed in default config and type templates pages. Also, the type template form shows the description and change reason twice
Show a delete prompt and remove duplicate fields
https://github.com/user-attachments/assets/d29819bf-97e1-4248-aa6c-09c13247ee8c
closes #399
=> fix: show delete prompt for delete actions

crates/frontend/src/components/default_config_form.rs
=> fix: removed err as a default value for schema type and enum variants

crates/context_aware_config/src/api/config/handlers.rs
Scope is being moved out
```
error[E0382]: use of moved value: `scope`
#33 164.3    --> superposition/crates/context_aware_config/src/api/config/handlers.rs:62:5
#33 164.3     |
#33 164.3 55  |     let scope = Scope::new("")
#33 164.3     |         ----- move occurs because `scope` has type `actix_web::Scope`, which does not implement the `Copy` trait
#33 164.3 ...
#33 164.3 61  |     scope.service(get_config_fast);
#33 164.3     |           ------------------------ `scope` moved due to this method call
#33 164.3 62  |     scope
#33 164.3     |     ^^^^^ value used here after move
#33 164.3     |
#33 164.3 note: `actix_web::Scope::<T>::service` takes ownership of the receiver `self`, which moves `scope`
#33 164.3    --> /usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/actix-w …
```
=> fix: scope ownership in get config HP mode

Cargo.lock, crates/frontend/Cargo.toml, crates/frontend/src-js/utils.js, crates/frontend/src/components/default_config_form.rs, crates/frontend/src/components/dimension_form.rs, crates/frontend/src/components/input.rs, crates/frontend/src/components/monaco_editor.rs, crates/frontend/src/components/type_template_form.rs, nix/rust.nix
- Monaco input type now accepts a vector of json values to be used for completions.
- Added JS-FFI(via wasm-bindgen) to create a monaco completions object. This is required as we have to call another JS-FFI to register this object, and that FFI itself accepts a foreign JS type, so needed to write the constructor in JS.
- Completions get registered on render & cleaned up on de-render.
=> feat: Added support for completions in monaco editor.

crates/context_aware_config/src/api/default_config/handlers.rs, crates/frontend/src/api.rs, crates/frontend/src/pages/context_override.rs, crates/frontend/src/pages/default_config.rs, crates/frontend/src/pages/experiment.rs, crates/frontend/src/pages/experiment_list.rs, crates/superposition_types/src/api.rs, crates/superposition_types/src/api/default_config.rs
Default config screen is paginated, but provides no way to search for a key
Provide a filter to find config keys
https://github.com/user-attachments/assets/d52d23dd-b7de-4954-bb38-3e1801365508
=> feat: add key filter for default config

crates/frontend/src/logic.rs
params for resolve being sent with the operator like: `key==value`, `keyinvalue`, instead of a simple `key=value`.
For resolve a simple assign is expected and no other operator
example:
`http://localhost:8080/config/resolve?clientId==studio1&platform==web&show_reasoning=true`
Generate `key=value` while generating the params only, operators other than `==` are not expected in this flow
=> fix: Params being sent in resolve page

crates/frontend/src/components/delete_modal.rs
sticky content of the tables are overlapping with the delete modal, as no z-index has been provided to the backdrop of the delete modal
Add a high z-index value to the modal backdrop
=> fix: z-index of delete modal

crates/frontend/src/logic.rs
When `in` operator is used, the default value of the input instead of being `[]` is currently being used as `[""]`, `[false]`, `[0]` for string, boolean, integer arrays and so on
Use `[]` as the default value for `in` operator
=> fix: Default value for dimensions while using in operator

crates/frontend/src/components/context_card.rs, crates/frontend/src/components/experiment_form.rs, crates/frontend/src/pages/context_override.rs, crates/frontend/src/pages/experiment.rs, crates/frontend/src/pages/experiment_list.rs, crates/frontend/src/types.rs
Create Experiments From Overrides
Added create experiment popup to overrides
=> feat : Create Experiments From Overrides

Cargo.lock, crates/experimentation_platform/src/api/experiments/handlers.rs, crates/experimentation_platform/src/api/experiments/types.rs, crates/frontend/src/components/button.rs, crates/frontend/src/components/context_form/utils.rs, crates/frontend/src/components/experiment_form/utils.rs, crates/frontend/src/components/input.rs, crates/frontend/src/logic.rs, crates/frontend/src/pages/experiment_list.rs, crates/frontend/src/pages/experiment_list/utils.rs, crates/frontend/src/pages/home.rs, crates/frontend/src/types.rs, crates/frontend/tailwind.config.js, crates/superposition_types/Cargo.toml, crates/superposition_types/src/database/models/experimentation.rs
It is hard to search for experiments
Add the ability to filter and manage experiments. Search is done on the backend, so even paginated experiments can be searched for
https://github.com/user-attachments/assets/cc9f1344-fc7b-4868-885f-65f2a3085703
=> feat: experiment filters in UI

.github/workflows/generate_client_bundles.yaml, crates/cac_client/src/interface.rs, crates/experimentation_client/src/interface.rs, scripts/setup_client.sh
We don't generate distributive binaries for our clients
Add a workflow to generate builds for linux, macOS and update interface.rs to support windows builds in the future.
=> feat: generate multiple binaries for clients based on platform

crates/frontend/src/logic.rs
Context with an empty `and` block evaluates as false for all cases.
Prevent adding `and` block if the context is empty from frontend.
=> fix: removing `and` block if context is empty

smithy/models/organisation.smithy
Refactored organisation smtihy model w/ mixin for requests. I thought that smithy fields could not be redefined after using a mixin but looks like you can if you don't change the type, see: https://smithy.io/2.0/spec/mixins.html#mixin-members-must-not-conflict
Courtesy: @sauraww
=> refactor: Refactored organisation smtihy model w/ mixin for requests.

crates/frontend/src/pages/experiment_list.rs
date can't be selected in experiments page filter beyond a month
Set different min date for experiments
=> fix: set a sensible min for experiments date filter

crates/context_aware_config/src/api/dimension/handlers.rs, crates/superposition_types/migrations/2024-12-05-172909_dimension_priority_default/up.sql, docker-compose/postgres/db_init.sql, workspace_template.sql
Delete dimension is not working and it gives , issue was in constraint instead of initially immediate
it should be initially deferred.
also without deferrable constraints create/update/delete apis not working , so deferrable is necessary
Constraint Type | Can Be Deferred? | Enforced When? | Behavior in Your Case
-- | -- | -- | --
UNIQUE (position) (non-deferrable) | ❌ No | Always immediately | ❌ Fails due to temporary duplicates
UNIQUE (position) DEFERRABLE INITIALLY IMMEDIATE | ✅ Yes | By default, immediately  (but deferrable by planner if safe) | ✅ Works, because PG planner handles it smartly
Things …
=> fix delete dimension bug

crates/frontend/src/query_updater.rs
when prefix is enabled the route gets changed to => `prefix/prefix`
route to a prefix stripped url, as leptos auto adds the prefix when `use_navigate` is used
=> fix: Auto query reader for service prefix

crates/frontend/src/pages/config_version_list.rs, crates/frontend/src/pages/context_override.rs, crates/frontend/src/pages/default_config.rs, crates/frontend/src/pages/dimensions.rs, crates/frontend/src/pages/experiment_list.rs, crates/frontend/src/pages/function/function_list.rs, crates/frontend/src/pages/workspace.rs, crates/frontend/src/query_updater.rs, crates/superposition_derives/Cargo.toml, crates/superposition_derives/src/lib.rs, crates/superposition_types/Cargo.toml, crates/superposition_types/src/api/context.rs, crates/superposition_types/src/api/experiments.rs, crates/superposition_types/src/custom_query.rs, crates/superposition_types/src/lib.rs
When reading params from url and no params are being provided in frontend, since all keys of the filter being `Option` type leads to the type getting successfully created with all as `None` values.
This leads to the default value not being used as the extract was a success.
For experiments, default time range is last `30days` in the type and last `24hours` in the backend, so when no params are sent to frontend, it is not going to the type default. Thus `experiments` of last 24 hours are being shown.
1. Added `extract_non_empty` function to extract query and fallback to default if all keys are `None`
2. Added `IsEmpty` proc_macro_derive to auto derive `IsEmpty` trait for structs having `Named` fields
3. Added check in `use_param_updater` to consider `no params` and `default params` …
=> fix: Empty check for keys of struct

crates/frontend/src/components/table.rs
string slicing fails with non ASCII characters
use `take` on slice of `chars`
=> fix: String splice in table component

Cargo.toml, crates/context_aware_config/src/api/functions/handlers.rs
Issue #473 
Removed explicit match for FKValidation. Using the ? operator to let the error propagate. It should now be handled by AppError by default
None
None
None
=> fix: removed explicit err handling for FKValidation & removed redundant crate

crates/frontend/src/api.rs, crates/frontend/src/components/experiment_form.rs, crates/frontend/src/pages/context_override.rs
On updating/cloning/experimenting on a override after a key filter has been applied, the operation is done only with the remaining set of keys
use the context id to fetch the data of the context on which the operation is to be performed
=> fix: Override update/clone/experiment after key filter

Dockerfile
docker build -t . fails since we are trying to copy a toml file does not exist
Remove said line from the docker file
If this file get's added back. We need to ensure the copy operation is added back as well
=> fix: Removed copy of superposition.cac.toml, since the file was removed in an earlier revision

crates/superposition/src/main.rs
The Superposition server logs do not print a single log line for requests.
This can be enabled by include the default implementation of the Logger middleware supplied by actix.
None
None
None
None
```log
[2025-07-08T16:47:50Z INFO  actix_web::middleware::logger] 127.0.0.1 "GET /workspaces?all=true HTTP/1.1" 200 1066 "-" "-" 0.025802
[2025-07-08T16:47:50Z INFO  actix_web::middleware::logger] 127.0.0.1 "GET /default-config?all=true& HTTP/1.1" 200 2045 "-" "-" 0.006340
[2025-07-08T16:47:50Z INFO  actix_web::middleware::logger] 127.0.0.1 "GET /admin/localorg/test/default-config?all=true&grouped=true HTTP/1.1" 200 …
```
=> chore(logs): enable access log for each actix request

.github/workflows/release.yaml, clients/java/build.gradle.kts
Gradle/npm/twine is broken in the build - https://github.com/juspay/superposition/actions/runs/16373708049/job/46269070025
Fix gradle publishing reference by including the plugin
NA
NA
NA
NA
NA
=> build: fix gradle/python/npm publish

.github/workflows/release.yaml
The auth for private npm registry needs to be setup before the setup-node action.
This moves the aws auth stuff before the setup-node action
NA
NA
NA
NA
NA
=> build: fix npm issue

README.md, docs/docs/intro.md
The package repository images in the clients table are not linked to the repository webpages as shields injecting links does not seem to work as expected in markdown.
Links are added
NA
NA
NA
NA
NA
=> docs: fix package links 

examples/cac_redis_module/README.md, examples/k8s-staggered-releaser/README.md
The k8s-staggered-releaser and the cac_redis_module examples do not have docs on what they do and how to test them out.
Add the docs
NA
NA
NA
NA
NA
=> docs: add README.md for examples

.github/workflows/release.yaml, docs/docs/applications/_category_.json, docs/docs/applications/cac-redis-module.md, docs/docs/applications/k8s-staggered-releaser.md, docs/docs/basic-concepts/context-aware-config.md, docs/docs/basic-concepts/experimentation.md, docs/docs/quick_start.mdx, docs/src/constants/versions.js
* The documentation for the examples are missing in the docusaurus website.
* The documentation for functions/template types and webhooks are missing in the documentation website as well.
* The versions for the provider libraries are hard-coded in the docs.
This PR adds the missing documentation and makes the versions dynamic - picking it up from the release.
NA
NA
NA
NA
NA
=> docs: add docusaurus docs for examples

crates/experimentation_client/src/lib.rs, crates/frontend/src/api.rs, crates/frontend/src/pages/compare_overrides/types.rs, crates/frontend/src/pages/default_config_list/types.rs, crates/frontend/src/pages/function/types.rs, crates/frontend/src/query_updater.rs, crates/superposition_derives/src/lib.rs, crates/superposition_types/src/api/context.rs, crates/superposition_types/src/api/default_config.rs, crates/superposition_types/src/api/experiment_groups.rs, crates/superposition_types/src/api/experiments.rs, crates/superposition_types/src/api/functions.rs, crates/superposition_types/src/custom_query.rs
Similar `Display` trait being written over and over for different struct for converting the struct to query param format. 
This often leads to confusion as to why a field is missed as it might not have been added in the implementation of the `Display` trait
Added `QueryParam` proc_macro_derive which derives the QueryParam trait for the struct to get the desired query param. 
It being auto generated makes sure that newly added fields get auto added to the `QueryParam` trait's implementation
=> feat: Add QueryString proc_macro_derive
